sudo: required
language: csharp

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - ARTIFACTS_PATHS=./artifacts
  - secure: tHhDFo5fTDSLNBaNVPzg4VIlq0xr6QQ/MR4Cn/LMymGgfypPpgcxKunQ2mHdRD2HHwzrzLqqJHyENKeftL8PS0lrgzmb3Uwrd8vaamSBnCC8p8bCDorfJzEQ9lzkTc1ZvBz4yQpOhoPtLAsSRq3nfdvviN1pkPFWdOShI1N5oO4yaSDz6P7KRlPq+bKgA61KrOa6A1R0UyoB90usGC1kNt0gUcy1Qv0vWKxIJWcyGNQBiYbA1k22Raw21yrRYiE513Bv89/wqsTqADUcXtcCbIM68V648DD/Ti7dr2e9oNRxXesGVaYXwtIxmiV34AYIydkfVyDowQ+qyNKEgY4Fhqzx1QM6fLpAoTEXXXEBrOQw4SVUZwOtMGHbRuCP8XtC9pkCQohp48MBJObXbDDZ5QoKOc6H6dKd2+ppYY/PBsqALUz58gSpkgO6qP7Wc0GVo7W5fT8Mml2w8gwiht54nmJhcYdxCGkFaz7+D+1iX2kkdpjbGMcxX0B88nqOH0vmTvut3am2cCFoiYAK6DV5XEBDxqDQ0iGE539k+KE/oRA4cC76AjHAFyO+mOdjgXhVN713Q/yGifgbBsHimua8E8t/Ki2K+J+10T0yB/ahAIKcSJJOYRS0jqgNrB5aGz8Rv9YAbixJvF/JdmPOTfYGaiTjX7imt460NgIt4440Pzs=

install:
  - sudo apt-get install -y jq
  - DNX_VERSION="1.0.0-rc1-update1"
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_USER_HOME=$DNX_USER_HOME DNX_BRANCH=v$DNX_VERSION sh
  - source ~/.dnx/dnvm/dnvm.sh && dnvm install $DNX_VERSION -alias default && dnvm alias default | xargs -i ln -s ~/.dnx/runtimes/{} ~/.dnx/runtimes/default
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm install semver -g
 
before_script:
  - chmod u+x build.sh
  - chmod u+x ./scripts/set-build-version.sh
  - chmod u+x ./scripts/patch-version.sh
  - eval $(./scripts/set-build-version.sh)
  - ./scripts/patch-version.sh --version=$PROJECT_BUILD_VERSION
  - bash -c "source ~/.dnx/dnvm/dnvm.sh"
  - export PATH=$PATH:$HOME/.local/bin
  - mono --version
  - dnu --version
  - dnvm list
  
script:
 - ./build.sh --version=$PROJECT_BUILD_VERSION --configuration=RELEASE --outputFolder=./artifacts --pack
