version: '3.1'
  
networks:
  idsrvnet:
    driver: overlay

services:
  idsrv-proxy:
    image: idsrv-proxy
    build:
      context: ./source/NginxProxy/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks: 
      - idsrvnet
    links:
      - idsrv4
      - mvcclient
      - mongodb
      - registration
  idsrv4:
    image: idsrv4
    build:
      context: ./source/IdSrv4/bin/PublishOutput/
      dockerfile: Dockerfile
    volumes: 
      - ./source/IdSrv4/bin/PublishOutput/:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    networks: 
      - idsrvnet
  mvcclient:
    image: mvcclient
    build:
      context: ./source/MvcClient/bin/PublishOutput/
      dockerfile: Dockerfile
    volumes:
      - ./source/MvcClient/bin/PublishOutput/:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    networks: 
      - idsrvnet
    extra_hosts: 
      login.127.0.0.1.xip.io: 192.168.10.21 # Edit this to be your local IP address of your computer.
  registration:
    image: registration
    build:
      context: ./source/Registration/bin/PublishOutput/
      dockerfile: Dockerfile
    volumes: 
      - ./source/Registration/bin/PublishOutput/:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    networks: 
      - idsrvnet
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=./stack/data/db
      - MONGO_LOG_DIR=./stack/dev/null
    volumes:
      - ~/AspNetCore.Identity.MongoDB/Samples/data/db:/data/db
    ports:
      - 27017:27017
    networks: 
      - idsrvnet
    command: mongod --smallfiles --logpath=/dev/null # --quiet    