version: '3.1'
  
services:
  idsrv-proxy:
    image: idsrv-proxy
    build:
      context: ./source/NginxProxy/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    network_mode: bridge
    links:
      - idsrv4
      - mvcclient
      - mongodb
      - registration
  idsrv4:
    image: idsrv4
    build:
      context: ./source/IdSrv4/bin/PublishOutput/
      dockerfile: Dockerfile
    volumes: 
      - ./source/IdSrv4/bin/PublishOutput/:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    network_mode: bridge
  mvcclient:
    image: mvcclient
    build:
      context: ./source/MvcClient/bin/PublishOutput/
      dockerfile: Dockerfile
    volumes:
      - ./source/MvcClient/bin/PublishOutput/:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    network_mode: bridge
  registration:
    image: registration
    build:
      context: ./source/Registration/bin/PublishOutput/
      dockerfile: Dockerfile
    volumes: 
      - ./source/Registration/bin/PublishOutput/:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    network_mode: bridge
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=./stack/data/db
      - MONGO_LOG_DIR=./stack/dev/null
    volumes:
      - ~/AspNetCore.Identity.MongoDB/Samples/data/db:/data/db
    ports:
      - 27017:27017
    network_mode: bridge
    command: mongod --smallfiles --logpath=/dev/null # --quiet    